class { 'druid':
  extensions_coordinates => [
    'io.druid.extensions:druid-s3-extensions',
    'io.druid.extensions:druid-histogram',
    'io.druid.extensions:mysql-metadata-storag',
  ],
  extensions_default_version          => '0.8.0',
  zk_paths_properties_path            => 'test_prop',
  zk_paths_announcements_path         => 'test_announ',
  zk_paths_live_segments_path         => 'test_live_segs',
  zk_paths_load_queue_path            => 'test_lq_path',
  zk_paths_coordinator_path           => 'test_co_path',
  zk_paths_indexer_base               => 'test_base',
  zk_paths_indexer_announcements_path => 'test_announcements_path',
  zk_paths_indexer_tasks_path         => 'test_task_path',
  zk_paths_indexer_status_path        => 'test_status_path',
  zk_paths_indexer_leader_latch_path  => 'test_leaser_latch_path',
  request_logging_type                => 'emitter',
  request_logging_feed                => 'druid_feed',
}
